CREATE TABLE `users`(
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(128) NOT NULL UNIQUE COMMENT'用户真实',
`avatar` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户头像的url,本地路径',
`role` TEXT NOT NULL COMMENT'角色权限，由LaravelORM模型将表层的数组类型存储为底层的字符串类型 admin和employee，默认admin',
`password` VARCHAR(32) NOT NULL COMMENT'MD5加密后的密码',
`age` INT(4) NOT NULL COMMENT'年龄',
`mobile` VARCHAR(11) NOT NULL COMMENT'手机',
`salary` FLOAT(8,2) NOT NULL COMMENT'薪水',
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
`deleted_at` TIMESTAMP NULL DEFAULT NULL,
`status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态 1：正常 0：不正常',
PRIMARY KEY (`id`)
)CHARSET = UTF8 ENGINE = MyISAM COMMENT '用户表';
alter table `users` AUTO_INCREMENT=101;

CREATE TABLE `foods`(
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`title` VARCHAR(64) NOT NULL COMMENT'菜名',
`price` FLOAT(8,2) NOT NULL COMMENT'原价，单位元',
`offprice` FLOAT(8,2) NOT NULL DEFAULT 0.00 COMMENT'折后价，单位元',
`type` VARCHAR(32) NOT NULL COMMENT'分类',
`img` VARCHAR(128) NOT NULL COMMENT'图片url',
`status` TINYINT NOT NULL DEFAULT 1 COMMENT'菜品状态，1：上架，0：下架',
`ordernum` INT DEFAULT 0 COMMENT'被点单次数',
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
`deleted_at` TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (`id`)
)CHARSET = UTF8 ENGINE = MyISAM COMMENT '菜品表';

CREATE TABLE `desks`(
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`status` TINYINT NOT NULL DEFAULT 0 COMMENT'1：有人，0无人',
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
`deleted_at` TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (`id`)
)CHARSET = UTF8 ENGINE = MyISAM COMMENT '餐桌表';

CREATE TABLE `orders`(
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`desk_id` INT(8) NOT NULL COMMENT'桌号',
`employee` VARCHAR(64) NOT NULL COMMENT'员工真实姓名',
`money` FLOAT(10,2) NOT NULL COMMENT'总金额',
`status` TINYINT NOT NULL DEFAULT 1 COMMENT'1：未付款，2：已付款， 3：已取消 , 4:已结账??',
`cart_list` TEXT COMMENT'订单详情[["id":"",title:"",url:"",unitprice:"单价",quantity:"数量",total:"总价"]] 表层数组，底层由LaravelORM转为字符串',
`date_str` VARCHAR(16) NOT NULL COMMENT'下单日期YYYY-mm-dd格式',
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
`deleted_at` TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (`id`)
)CHARSET = UTF8 ENGINE = MyISAM COMMENT '订单表';